"""Quick verification that the compiled extension imports and loads.

Generated by Aero Universal.  Build the module first (e.g. `maturin develop`
or `cargo build --release` + copy the .so onto the Python path).
"""

import importlib
import sys

MODULE = "shbt_sim"


def main() -> int:
    try:
        mod = importlib.import_module(MODULE)
    except ImportError as exc:
        print(f"[FAIL] could not import {MODULE!r}: {exc}")
        print("       build it first: `cargo build --release` / `maturin develop`")
        return 1
    print(f"[ OK ] imported {MODULE!r} -> {mod!r}")
    print("       exported attributes:", [a for a in dir(mod) if not a.startswith("_")])
    return 0


if __name__ == "__main__":
    sys.exit(main())
